### PR TITLE
Adding States and Version Filtering

### PR DESCRIPTION
**Pull request by nikhiltjoy**

### CODE REVIEW

**Comment by mpderbec** [comment]
I don't think we're handling the case where there are no test results at all yet... I tested that and those seem to be showing up as PASS.

**Comment by nikhiltjoy** [comment]
so in that scenario, how do you know that a step should have test results? is it set in stone that all steps must have test results?

**Comment by mpderbec** [comment]
Assume yes. If a step does not have results, it is incomplete.

**Comment by nikhiltjoy** [comment]
Okay, I'll fix that then.

On Wednesday, May 13, 2015, mpderbec notifications@github.com wrote:

> Assume yes. If a step does not have results, it is incomplete.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/seeq12/barrow/pull/2#issuecomment-101827295.

## 

Nikhil Thomas Joy
University of Waterloo
Electrical Engineering - 2016

**Comment by mpderbec** [comment]
Also-- can you make it so that all nodes are expanded by default? (instead of collapsed)

**Comment by nikhiltjoy** [comment]
i've made all the nodes expanded, and made the state of a step incomplete if it doesn't have any tests

**Pull request merged**
